const productos = [
    {
      nombre: "Sol",
      estilo:"Lager",
      precio: 220,
      ibu: 20,
      precioUnidad: 200,
      img: "./fotos/sol.png",
      cantidad: 1,
      id: 0,
    },
    {
      nombre: "Strange ",
      estilo:"Cuadruple Ipa",
      precio: 450,
      ibu: 70,
      precioUnidad: 450,
      img: "./fotos/ipa4.png",
      cantidad: 1,
      id: 1,
    },
    {
      nombre: "ASTOR & MUR & STRANGE ",
      estilo: "Old Ale",
      precio: 440,
      ibu: " -",
      precioUnidad: 440,
      img: "./fotos/oldAle.png",
      cantidad: 1,
      id: 2,
    },
    {
      nombre: "Strange",
      estilo: "Ipa",
      precio: 370,
      ibu: 58,
      precioUnidad: 370,
      img: "./fotos/ipaStrange.png",
      cantidad: 1,
      id: 3,
    },
    {
      nombre: "Goose Island ",
      estilo:"Ipa",
      precio: 310,
      ibu: 55,
      precioUnidad: 310,
      img: "./fotos/ipaGooseIsland.png",
      cantidad: 1,
      id: 4,
    },
  ];

